# Generated by Django 6.0 on 2025-12-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-status', '-priority']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[(4, 'Low'), (3, 'Medium'), (2, 'High'), (1, 'Urgent')], default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Resolved'), (4, 'Closed')], default=1, max_length=20),
        ),
    ]
